import {  timestamp, boolean, bigint } from 'drizzle-orm/pg-core';

/** Standard primary key: bigint generated by default as identity. */
export const idColumn = () => bigint('id', { mode: 'number' }).primaryKey().generatedByDefaultAsIdentity();

/** Standard audit timestamp trio. */
export const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
};

/** Standard active/enabled flag. */
export const isActiveColumn = () => boolean('is_active').default(true).notNull();
