import { uuid, timestamp, boolean } from 'drizzle-orm/pg-core';

/** Standard primary key: uuid, randomly generated by Postgres (pgcrypto). */
export const idColumn = () => uuid('id').defaultRandom().primaryKey();

/** Standard audit timestamp trio. */
export const timestamps = {
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
};

/** Standard active/enabled flag. */
export const isActiveColumn = () => boolean('is_active').default(true).notNull();
